### ISSUE TITLE
User info breaks on Swift keys

### ISSUE THREAD

**Issue by bibby** [valerytschopp/python-radosgw-admin#8]
I'll have to return with the specific Ceph/RadowGW version,  but `get_users` breaks [here](https://github.com/valerytschopp/python-radosgw-admin/blob/master/radosgw/user.py#L96) due to `key_dict` not having an `access_key` property.

My dicts have only `secret_key` and `user`.

**Comment by valerytschopp** [comment]
Without knowing the radosgw version, it is difficult to assess the problem

**Comment by bibby** [comment]
I apologize for not keeping my promise to return. The cluster where I can replicate this is `ceph version 10.2.6 (656b5b63ed7c43bd014bcafd81b001959d5f089f)`.

Soon, we'll have a newer cluster that I could try, if I remember.

**Comment by bmeekhof** [comment]
I just put in a PR.  Here is a little more info on the problem for reference:


```
Traceback (most recent call last):
  File "./rgwadmin-test2.py", line 14, in <module>
    all = rgwadmin.get_users()
  File "/usr/local/lib/python3.6/site-packages/radosgw/connection.py", line 172, in get_users
    user = self.get_user(uid)
  File "/usr/local/lib/python3.6/site-packages/radosgw/connection.py", line 193, in get_user
    user = UserInfo(self, user_dict)
  File "/usr/local/lib/python3.6/site-packages/radosgw/user.py", line 56, in __init__
    self._update_from_user(user_dict)
  File "/usr/local/lib/python3.6/site-packages/radosgw/user.py", line 96, in _update_from_user
    key_dict['access_key'], key_dict['secret_key'],
KeyError: 'access_key'
```

**Comment by valerytschopp** [comment]
#22 should fix the issue
